import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ProductCard from "@/components/Cards/ProductCard"
import ProductCardPage from "@/components/Cards/ProductCardPage";
import Sidebar from "@/components/Navbar/sidebar/Sidebar";
import Loader from "@/components/Loader/Loader";
import Header from "@/components/Header/Header";
import BlogPage from "@/components/BlogPage/BlogPage";
import AboutUs from "@/components/AboutUs/AboutUs";
import RegisterVenue from "@/components/Register/RegisterVenue";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar/> */}
        {/* <Header /> */}
        {/* <ProductCardPage /> */}
        {/* <BlogPage/> */}
        {/* <AboutUs/> */}
        {/* <Loader /> */}
        <RegisterVenue/>
        {children}
      </body>
    </html>
  );
}
