import type { Metadata } from "next";
import { Poppins } from '@next/font/google'
import "./globals.css";
import VenueNavbar from "@/components/Navbar/VenueNavbar/VenueNavbar";
import Footer from "@/components/Footer/Footer";
import Provider from "@/components/Provider";
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
})
export const metadata: Metadata = {
  title: "Nimtoz",
  description: "Generated by T4T",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <Provider>
          {/* <header className="z-50">
          <VenueNavbar />
        </header> */}
          {/* <main className="pt-[5rem] lg:pt-[6.6rem] flex w-full z-0">
          <VenueSidebar />
        </main>
        <ProductDetailPage/> */}
          <main>
            {children}
            <ToastContainer position="bottom-right"/>
          </main>
          {/* <Toast /> */}
          {/* <Footer /> */}
        </Provider>
      </body>
    </html>
  );
}
